// Maps "{routeId}-{direction}" to the typical terminal station name.
// Some routes branch; this shows the most common terminus.
// Actual trip destinations can vary — a future enhancement can load static GTFS trips.txt.
export const TERMINUS_MAP: Record<string, string> = {
  '1-N': 'Van Cortlandt Park - 242 St',
  '1-S': 'South Ferry',
  '2-N': 'Wakefield - 241 St',
  '2-S': 'Flatbush Av - Brooklyn College',
  '3-N': 'Harlem - 148 St',
  '3-S': 'New Lots Av',
  '4-N': 'Woodlawn',
  '4-S': 'Crown Hts - Utica Av',
  '5-N': 'Eastchester - Dyre Av',
  '5-S': 'Flatbush Av - Brooklyn College',
  '5X-N': 'Eastchester - Dyre Av',
  '5X-S': 'Flatbush Av - Brooklyn College',
  '6-N': 'Pelham Bay Park',
  '6-S': 'Brooklyn Bridge - City Hall',
  '6X-N': 'Pelham Bay Park',
  '6X-S': 'Brooklyn Bridge - City Hall',
  '7-N': 'Flushing - Main St',
  '7-S': '34 St - Hudson Yards',
  '7X-N': 'Flushing - Main St',
  '7X-S': '34 St - Hudson Yards',
  'A-N': 'Inwood - 207 St',
  'A-S': 'Far Rockaway / Lefferts Blvd',
  'B-N': '145 St',
  'B-S': 'Brighton Beach',
  'C-N': '168 St',
  'C-S': 'Euclid Av',
  'D-N': 'Norwood - 205 St',
  'D-S': 'Coney Island - Stillwell Av',
  'E-N': 'Jamaica Center - Parsons/Archer',
  'E-S': 'World Trade Center',
  'F-N': 'Jamaica - 179 St',
  'F-S': 'Coney Island - Stillwell Av',
  'FS-N': 'Prospect Park',
  'FS-S': 'Franklin Av',
  'G-N': 'Court Sq',
  'G-S': 'Church Av',
  'GS-N': 'Times Sq - 42 St',
  'GS-S': 'Grand Central - 42 St',
  'H-N': 'Far Rockaway - Mott Av',
  'H-S': 'Broad Channel',
  'J-N': 'Jamaica Center - Parsons/Archer',
  'J-S': 'Broad St',
  'L-N': '8 Av',
  'L-S': 'Canarsie - Rockaway Pkwy',
  'M-N': 'Forest Hills - 71 Av',
  'M-S': 'Middle Village - Metropolitan Av',
  'N-N': 'Astoria - Ditmars Blvd',
  'N-S': 'Coney Island - Stillwell Av',
  'Q-N': '96 St',
  'Q-S': 'Coney Island - Stillwell Av',
  'R-N': 'Forest Hills - 71 Av',
  'R-S': 'Bay Ridge - 95 St',
  'S-N': 'Times Sq - 42 St',
  'S-S': 'Grand Central - 42 St',
  'SI-N': 'St George',
  'SI-S': 'Tottenville',
  'W-N': 'Astoria - Ditmars Blvd',
  'W-S': 'Whitehall St - South Ferry',
  'Z-N': 'Jamaica Center - Parsons/Archer',
  'Z-S': 'Broad St',
};
